In [ ]:
1)Numpy kutubxonasini import qilish va massiv yaratish:

In [1]:
import numpy as np

# 1-dimentional array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2-dimentional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
2)Nol va birliklar massivi yaratish:

In [2]:
zeros = np.zeros((3,3))
print(zeros)

ones = np.ones((3,3))
print(ones)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
3)Arifmetik operatsiyalar:

In [3]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])

# Addition
print(x + y)

# Subtraction
print(x - y)

# Multiplication
print(x * y)

# Division
print(x / y)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
4)Indeksatsiya va kesim:

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Get the element at index 1
print(arr[1])

# Get the elements from index 1 to 5
print(arr[1:6])


2
[2 3 4 5 6]


In [ ]:
5)Numpy massivlari ustida statistik operatsiyalar:

In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(arr))

# Median
print(np.median(arr))

# Standard Deviation
print(np.std(arr))


3.0
3.0
1.4142135623730951
